# Generated by Django 4.2.16 on 2024-12-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa_app', '0002_rename_consultations_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
