# Generated by Django 4.2.16 on 2024-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa_app', '0003_consultation_message_alter_consultation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
