# Generated by Django 4.2.16 on 2024-12-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasa_app', '0005_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptoms_input',
            new_name='SymptomsInput',
        ),
    ]
